##### 1. What does Pandas stand for?
- The Pandas package stands for Python Data Analysis.
##### 2. What are the 2 collections used in Pandas?
- Series and DataFrames
##### 3. Name 4 things Pandas can do for us.
- Data cleansing, loading and saving data, statistical analysis and data dill.
##### 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
- The keyword is inplace, which will modify the underlying data if set to True.
##### 5. What is a CSV
- CSV stands for Comma Separated Values which is a type of file that uses commas to separate the values.
##### 6. When cleaning data what values do we not like in our data?
- Null values are not liked as well as incorrect data which could be a string in a integer column.

In [5]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). 
# You can use the reshape method -- .reshape()
import numpy as np
array_3d = np.arange(12).reshape((2,3,2))
array_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [9]:
# 8 Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
import copy
import numpy as np

array2 = np.linspace(0,20,num=6)
print("The answer to number 8 is ...\n",array2)

#  9. Make a Deep Copy of the above array
array2_1 = copy.deepcopy(array2)
print("The answer to number 9 is ...\n",array2_1)

The answer to number 8 is ...
 [ 0.  4.  8. 12. 16. 20.]
The answer to number 9 is ...
 [ 0.  4.  8. 12. 16. 20.]


In [36]:
# 10: Using NumPy, 'broadcast' the multiplication of the following 2 
# arrays below to a 2-D array using the newaxis parameter ...
import numpy as np

array_a = [0.71, 0.1, 0.24, 0.3]
array_b = [0.8, 0.59, 1.0, 1.11]

array_c = np.multiply(array_a,array_b)
print("The answer to number 10 is ...\n",array_c[:, np.newaxis])
print(array_c[:, np.newaxis].shape)

The answer to number 10 is ...
 [[0.568]
 [0.059]
 [0.24 ]
 [0.333]]
(4, 1)


In [8]:
# 11. Concatenate these 3 arrays into a new array named 'newArray'...
import numpy as np

arr1 = ([[25, 16]])
arr2 = ([[11, 2], [13, 4]])
arr3 = ([[7, 81], [5, 6], [11, 12]])
newArray = np.concatenate((arr1,arr2,arr3))

print("The answer to number 11 is ...\n",newArray)
print(newArray.shape)

# 12. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print("\nThe answer to number 12 is ...\n",sortedArray)

# 13. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', 
# so it has 2 dimensions with a size of 2, 3.

reshapedArray = sortedArray.reshape(2,2,3)
print("\nThe answer to number 13 is ...\n",reshapedArray)

# 14. Unpack the array tuples from the above 'reshapedArray' 
# into 4 well named variables. Print the 4 variables.

[[unpacked1, unpacked2], [unpacked3, unpacked4]] = reshapedArray
print(f"""\nFor question 14.... The first unpacked array is {unpacked1} 
\nand the second unpacked array is {unpacked2}
\nand the third unpacked array is {unpacked3}
\nand the fourth unpacked array is {unpacked4}
""")


The answer to number 11 is ...
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
(6, 2)

The answer to number 12 is ...
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

The answer to number 13 is ...
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]

For question 14.... The first unpacked array is [16 25  2] 

and the second unpacked array is [11  4 13]

and the second unpacked array is [ 7 81  5]

and the second unpacked array is [ 6 11 12]



In [46]:
# 15. Combined and sort the following arrays into one called 'comboArray' ...
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one,two,three)))

print(comboArray)

# 16. Take 'comboArray' and perform the following slicing activities:
# print sec1 - the 2nd element
print("\nThe second element is....",comboArray[1])
# print sec2 - all elements from the 3rd element to the last
print("\nThe elements from the 3rd element to the last are....\n",comboArray[2:])
# print sec3 - all elements from the 4th to the 14th elements
print("\nThe elements from the 4th to the 14th elements are....\n",comboArray[3:14])
# print sec4 - the last 6 elements
print("\nThe the last 6 elements are....",comboArray[-6:])
# print sec5 - all element from #0 up to and including #15, using 
# the negative number method, i.e. taking a section from the end.
print("\nThe elements from #0 up to and including #15 using neg # method are....\n",comboArray[-28:-10])
# print sec6 - from #20 every even element to the end
print("\nThe from #20 every even element to the end....",np.arange(comboArray[16],comboArray[23],2))
# print sec7 - from the last element moving forward, every 5th element.
print("\nThe last element moving forward, every 5th element is....",np.arange(comboArray[-1],comboArray[-24],-5))


[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

The second element is.... 1

The elements from the 3rd element to the last are....
 [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

The elements from the 4th to the 14th elements are....
 [ 3  4  5  6  7 10 11 12 13 14 15]

The the last 6 elements are.... [22 23 24 25 26 27]

The elements from #0 up to and including #15 using neg # method are....
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]

The from #20 every even element to the end.... [20 22 24 26]

The last element moving forward, every 5th element is.... [27 22 17 12  7  2]


In [50]:
# Skipping 17 to 19
# 20. Using Series, create a DataFrame that looks like this:
import pandas as pd

Ingredients = pd.Series(["Flour","Milk","Eggs","Spam"],name="Ingredients")
Quantity = pd.Series(["4","1","2","1"],name="Quantity")
Unit = pd.Series(["cups","cup","large","can"],name="Unit")

ShoppingListDF = pd.concat([Ingredients,Quantity,Unit],axis=1)
print(ShoppingListDF)

  Ingredients Quantity   Unit
0       Flour        4   cups
1        Milk        1    cup
2        Eggs        2  large
3        Spam        1    can


In [10]:
# Question 21
print("21. Take this data and create a DataFrame named studentData\n")
import pandas as pd
things =     {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

studentData = pd.DataFrame(things)
print(studentData)

# Question 22
print("""\n 22. Add a new column to the DataFrame with the following deserts: 
 ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"] """)
Deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData["Deserts"]=Deserts
print("\nUpdated DataFrame with deserts...\n",studentData)

# Question 23
print("""\n23. Sort the 'studentData' DataFrame in Ascending order -- 
Sorting by column 'Name' and then "address""")

studentData.sort_values(by=["Name","address"])


21. Take this data and create a DataFrame named studentData

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

 22. Add a new column to the DataFrame with the following deserts: 
 ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"] 

Updated DataFrame with deserts...
       Name  Height Qualification  address  Age        Pets           sport   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        D

Name  Height Qualification  address  Age        Pets           sport   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

In [66]:
# Question 24
print("""24. Save this DataFrame here below to disc as a .CSV file 
# with the name cows_and_goats.csv:\n""")
import pandas as pd
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv("cows_and_goats.csv",index=False)

df1 = pd.read_csv("cows_and_goats.csv")
print("\n My current inventory of my farm is....\n",df1)

24. Save this DataFrame here below to disc as a .CSV file 
# with the name cows_and_goats.csv:


 My current inventory of my farm is....
    Cows  Goats
0    12     22
1    20     19


In [65]:
# Question 25
print("""25. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.\n""")
# Create veggie dataframe
veggies = {
    "Name": ["Potato","Beets","Tomato","Celery","Spinach"],
    "Color": ["Brown","Red","Red","Green","Green"],
    "Liked": [True,False,True,False,True],
}
veggiesDF = pd.DataFrame(veggies)
print("\nCheck out this veggies list: \n",veggiesDF)
# Save veggie dataframe to CSV
veggiesDF.to_csv("VeggieList.csv",index=False)

# Open previously made CSV and add a new column
NewVeggieList = pd.read_csv("VeggieList.csv")
Good_On_Sandwich = ["No","Maybe","Yes","Probably Not","Yes"]
NewVeggieList["Good On Sandwich"] = Good_On_Sandwich

# Save new Veggie List and read then print results
NewVeggieList.to_csv("NEW_VeggieList.csv",index=False)
NewVeggieListDF = pd.read_csv("NEW_VeggieList.csv")
print("\nCheck out the latest on veggies: \n",NewVeggieListDF)

25. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.


Check out this veggies list: 
       Name  Color  Liked
0   Potato  Brown   True
1    Beets    Red  False
2   Tomato    Red   True
3   Celery  Green  False
4  Spinach  Green   True

Check out the latest on veggies: 
       Name  Color  Liked Good On Sandwich
0   Potato  Brown   True               No
1    Beets    Red  False            Maybe
2   Tomato    Red   True              Yes
3   Celery  Green  False     Probably Not
4  Spinach  Green   True              Yes
